<!DOCTYPE html>
<!-- Code is for the main page of the Abstract Eagle Technologies website it contains links to other pages-->
<!-- of the website and maybe login information along with our vision, mission, logo, and services -->

<html>
  <head>
    <title> AET Main page </title>
    <style>
    </style>
  </head>

  <body>
    <div>
      <ul>
        <li> Web developmet <
      </ul>
    </div>
  

<body>

</html>
