<!DOCTYPE html>
<!-- Code is for the main page of the Abstract Eagle Technologies website it contains links to other pages-->
<!-- of the website and maybe login information along with our vision, mission, logo, and services -->

<html>
  <head>
    <title> AET Main page </title>
    <style>
    </style>
  </head>

  <body>
 <!-- At the top of the page there will be the name"Abstract Eagle TEchnologies" in Garamond next to the logo -->
 <!-- below the name will be our vision and three values very simplified and made ot look like a subtitle-->
 <!-- right before the list of services we should list our mission, which is basically a more specific vision eg. vision: We want to go to the moon Mission: we provide the best communication tools for vehicles in transit to the moon-->
    
 <!-- This will be a section listing services we offer. When clicked on(or hovered over) it will expand with a more detailed description -->
    <div>
      <ul>
        <li> Front page Website developmet and design
        <li> Site Log in abilily
        <li> cloud based database 
        <li> Data anaylis( regression, modeling, cleanup)
        <li> various other Java, PHP,and C/C++ projects
      </ul>
    </div>
 <!-- Next will be a portfolio of projects/ reccomendations from past people we have worked with-->
 <!-- this could be on a second page but we should have either the ability to post stuff like a blog or 
 an insert that shows our most recent facebook page posts(from the FB page we are going to create)-->
    
 <!-- at the very b
  

<body>

</html>
